name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Cache npm dependencies to speed up builds

    - name: Install Dependencies
      run: |
        npm install
        npm install -D webpack-cli@5.1.4 # Explicitly install compatible version

    - name: Verify Webpack CLI Installation
      run: |
        npx webpack --version # Check if webpack-cli is installed correctly

    - name: Build
      run: |
        npx webpack

    - name: Upload Webpack Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: webpack-build-${{ matrix.node-version }}
        path: dist/
        retention-days: 7
